version: "3"

services:
  metaping.frontend:
    image: metapingfrontend:production
    container_name: metaping.frontend
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - metaping

networks:
  metaping:
    name: metaping
    external: false
